# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSale',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'itemPrices_itemsale',
                'managed': False,
            },
        ),
    ]
